sudo: required
services:
  - docker
env:
  NO_GCE_CHECK = true
language: java

#jdk:
#  - openjdk7
#  - oraclejdk8
      
before_install:
  - docker build -t spring-basic-1 -f Dockerfile.dev .

script:
  - mvn test -B