#FROM java:8
FROM maven:3.6.1-jdk-8-alpine AS MAVEN_TOOL_CHAIN
#VOLUME /tmp
WORKDIR '/java-spring-basic-1'
VOLUME m2/repository /root/.m2/repository

ADD src	./src
ADD pom.xml .
#ADD target/microservice.basic-0.0.1-SNAPSHOT.jar java-spring-basic-1.jar
RUN mvn test
RUN mvn package

RUN bash -c 'touch target/microservice.basic-0.0.1-SNAPSHOT.jar'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar target/microservice.basic-0.0.1-SNAPSHOT.jar"]
